### ISSUE TITLE
Bad Protocol

### ISSUE THREAD

**Issue by JollyPerson** [sauce420/anusoochak#3]
![20221216_140557.jpg](https://user-images.githubusercontent.com/18639773/208115626-fb262ba3-f362-4776-9280-2fa57e673bb7.jpg)

Use this instead

**Comment by jemsurfer** [comment]
Addressed in [this commit](https://github.com/sauce420/anusoochak/commit/4dae55bc97fd09bb9e5eda72b5e74853118716bb)
